# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1

executors:
  content-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_LOGIN # can specify string literal values
          password: $DOCKERHUB_TOKEN # or project environment variable reference
    working_directory: ~/repo

jobs:
  splunk-appinspect:
    executor: content-executor
    steps:
      - run:
          name: checkout repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/guilhemmarchand/telegraf-os
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/guilhemmarchand/telegraf-os
            fi
      - run:
          name: checkout Splunk Appinspect shell executor
          command: |
            git clone https://github.com/guilhemmarchand/splunk-appinspect-pipeline.git
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "telegraf-os/telegraf-os/default/app.conf" }}
      - run:
          name: run appinspect API app vetting
          command: |
            cd telegraf-os
            rm -rf telegraf-os/.git
            rm -rf telegraf-os/.circleci
            rm -rf telegraf-os/.gitignore
            tar -zcf telegraf-os.tar.gz telegraf-os
            mkdir dist
            cp telegraf-os.tar.gz dist/
            cd ../
            splunk-appinspect-pipeline/appinspect_vetting.sh --username=$SPLUNK_BASE_LOGIN --password=$SPLUNK_BASE_PASSWD --app=telegraf-os/dist/telegraf-os.tar.gz --included_tags=splunk_appinspect --excluded_tags=manual --excluded_checks=check_indexes_conf_does_not_exist --html_report_out=/tmp/appinspect_report.html
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "telegraf-os/telegraf-os/default/app.conf" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: telegraf-os/dist/
          paths:
            - telegraf-os.tar.gz
      - store_artifacts:
          path: /tmp/appinspect_report.html
          destination: appinspect-report
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
        auth:
          username: $DOCKERHUB_LOGIN # can specify string literal values
          password: $DOCKERHUB_TOKEN # or project environment variable reference
    steps:
      - attach_workspace:
          at: ~/telegraf-os/dist/telegraf-os.tar.gz
      - run:
          name: publish release on github
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/telegraf-os/dist/telegraf-os.tar.gz
workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - splunk-appinspect:
          context:
            - docker-hub-creds
            - splunk-base-creds
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          context: docker-hub-creds
          requires:
            - splunk-appinspect
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
